name: zyren_workspace
publish_to: none
environment:
  sdk: '>=3.10.0 <4.0.0'
workspace:
  - packages/zyren
  - packages/zyren_native
  - packages/flutter_zyren
  - packages/zyren_geospatial
  - examples/planet
  - examples/multiple_views
dev_dependencies:
  lints: ^6.0.0
