name: zyren_workspace
publish_to: none
environment:
  sdk: '>=3.10.0 <4.0.0'
workspace:
  - packages/zyren
  - packages/zyren_native
  - packages/zyren_gltf
  - packages/flutter_zyren
  - packages/zyren_inspector
  - packages/zyren_geospatial
  - examples/planet
  - examples/multiple_views
  - examples/model_viewer
  - examples/shader_lab
  - examples/shader_lab/effects_plugin
  - examples/shader_lab/effects_plugin/example
dev_dependencies:
  lints: ^6.0.0
