#!/usr/bin/env python3
"""Execute pinned source GLSL on a float-vector CPU host, without a renderer."""
from pathlib import Path
import argparse,base64,hashlib,json,re,struct,subprocess,tempfile,textwrap
parser=argparse.ArgumentParser()
parser.add_argument('source',type=Path)
args=parser.parse_args()
root=Path(__file__).resolve().parents[2]
folder=Path(__file__).parent
inventory=json.loads((root/'tool/reference/inventory.json').read_text())
hashes={v['path']:v['gitBlob'] for v in inventory['files']}
loaded={}
def read(name):
 path='packages/clouds/src/shaders/'+name
 code=(args.source/path).read_text()
 digest=hashlib.sha1(f'blob {len(code.encode())}\0'.encode()+code.encode()).hexdigest()
 assert digest==hashes[path],path
 loaded[path]=digest
 code=re.sub(r'/\*.*?\*/|//[^\n]*','',code,flags=re.S)
 code=re.sub(r'^\s*(?:#include|precision|uniform |in |layout\().*$', '',code,flags=re.M)
 code=re.sub(r'\bvec([234])\(',r'V\1(',code)
 code=re.sub(r'(?<![\w.])(\d+\.\d*(?:[eE][+-]?\d+)?|\d+[eE][+-]?\d+)(?![\w.])',r'\1f',code)
 return code
code=(folder/'compat.hpp').read_text()+read('perlin.glsl')+read('tileableNoise.glsl')
for filename,name,dim in [('localWeather.frag','weather',2),('cloudShape.frag','shape',3),('cloudShapeDetail.frag','detail',3),('turbulence.frag','turbulence',2)]:
 shader=read(filename)
 shader=shader.replace('void main() {', ('vec4' if dim==2 else 'float')+f' {name}(vec2 vUv,float layer) {{\n'+('vec4' if dim==2 else 'float')+' outputColor;')
 last=shader.rfind('}')
 shader=shader[:last]+'return outputColor;'+shader[last:]
 code+=shader
code+='''
void print(vec4 v){std::cout<<'['<<v.x<<','<<v.y<<','<<v.z<<','<<v.w<<']';}
int main(){std::cout<<std::setprecision(9)<<"[";int count=0;
for(int kind=0;kind<4;kind++) for(int y=0;y<8;y++) for(int x=0;x<8;x++){
 int z=(x*3+y*5)%8;vec2 uv=V2((x+.5f)/8,(y+.5f)/8);float layer=z/8.f;
 vec4 value=kind==0?weather(uv,0):kind==1?V4(shape(uv,layer)):kind==2?V4(detail(uv,layer)):turbulence(uv,0);
 if(count++)std::cout<<',';
 std::cout<<"{\\"kind\\":"<<kind<<",\\"size\\":8,\\"x\\":"<<x<<",\\"y\\":"<<y<<",\\"z\\":"<<z<<",\\"value\\":";print(value);std::cout<<'}';
}std::cout<<"]";}
'''
with tempfile.TemporaryDirectory(prefix='zyren-cloud-noise-') as temp:
 p=Path(temp);(p/'main.cpp').write_text(code)
 subprocess.run(['clang++','-O2','-std=c++17','-ffp-contract=off',str(p/'main.cpp'),'-o',str(p/'run')],check=True)
 result=json.loads(subprocess.check_output([str(p/'run')],text=True))
 diagnostic=code[:code.index('int main()')]+'''int main(){std::cout<<std::setprecision(9)<<"[";for(int i=0;i<128*171;i++){if(i)std::cout<<',';std::cout<<hash(float(i));}std::cout<<"]";}'''
 (p/'hash.cpp').write_text(diagnostic)
 subprocess.run(['clang++','-O2','-std=c++17','-ffp-contract=off',str(p/'hash.cpp'),'-o',str(p/'hash')],check=True)
 hashes=json.loads(subprocess.check_output([str(p/'hash')],text=True))
 packed=struct.pack('<'+'f'*len(hashes),*hashes)
 payload=base64.b64encode(packed).decode()
 dart="// Generated by tool/cloud_reference/noise.py from the pinned source float hash.\n"
 dart+="// SHA-256: "+hashlib.sha256(packed).hexdigest()+"\n"
 dart+="import 'dart:convert';\nimport 'dart:typed_data';\n\n"
 dart+="Float32List cloudNoiseHashes() {\n  final bytes=base64Decode(\n"
 dart+=''.join("    '"+line+"'\n" for line in textwrap.wrap(payload,100))
 dart+="  );\n  final data=ByteData.sublistView(bytes);\n  return Float32List.fromList([for(var i=0;i<bytes.length;i+=4) data.getFloat32(i,Endian.little)]);\n}\n"
 (root/'packages/zyren_geospatial/lib/src/clouds/noise_hash.dart').write_text(dart)
 output=root/'packages/zyren_geospatial/test/fixtures/clouds/noise.json'
 output.write_text(json.dumps({'revision':inventory['revision'],'sourceFiles':loaded,'precision':'CPU float, original GLSL, contraction disabled','samples':result},indent=2)+'\n')
 print(str(len(result))+' source noise samples')
