name: multiple_views
description: Native scene ownership and independent cameras.
publish_to: none
version: 0.1.0+1
resolution: workspace
environment:
  sdk: '>=3.10.0 <4.0.0'
dependencies:
  gpu3d_tools:
    path: ../../packages/gpu3d_tools
  gpu3d_devtools:
    path: ../../packages/gpu3d_devtools
  gpu3d_timeline:
    path: ../../packages/gpu3d_timeline
  gpu3d:
    path: ../../packages/gpu3d
  gpu3d_native:
    path: ../../packages/gpu3d_native
  flutter:
    sdk: flutter
  flutter_gpu3d:
    path: ../../packages/flutter_gpu3d
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
