name: multiple_views
description: Native scene ownership and independent cameras.
publish_to: none
version: 0.1.0+1
resolution: workspace
environment:
  sdk: '>=3.10.0 <4.0.0'
dependencies:
  zyren:
    path: ../../packages/zyren
  zyren_native:
    path: ../../packages/zyren_native
  flutter:
    sdk: flutter
  flutter_zyren:
    path: ../../packages/flutter_zyren
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
