name: multiple_views
description: Native scene ownership and independent cameras.
publish_to: none
version: 0.1.0+1
resolution: workspace
environment:
  sdk: '>=3.10.0 <4.0.0'
dependencies:
  zyren_engineering:
    path: ../../packages/zyren_engineering
  zyren_tools:
    path: ../../packages/zyren_tools
  zyren_devtools:
    path: ../../packages/zyren_devtools
  zyren_timeline:
    path: ../../packages/zyren_timeline
  zyren:
    path: ../../packages/zyren
  zyren_native:
    path: ../../packages/zyren_native
  flutter:
    sdk: flutter
  flutter_zyren:
    path: ../../packages/flutter_zyren
  path_provider: ^2.1.6
dev_dependencies:
  zyren_gltf:
    path: ../../packages/zyren_gltf
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/corners.png
    - assets/images/gray.jpg
