// Generated by tool/generate_ggx_energy.dart.
// Edit the canonical native ggx_energy.wgsl and regenerate.
const ggxEnergyWgsl = r'''
// Schlick A/B for correlated-Smith GGX. A+B is white directional albedo.
fn ggx_energy_integral(cosine: f32, roughness: f32, samples: u32) -> vec2<f32> {
    let nv = max(cosine,1e-4);
    let v = vec3(sqrt(1.-nv*nv),0.,nv);
    let alpha = max(roughness*roughness,.002025);
    let a2 = alpha*alpha;
    var sum = vec2(0.);
    for (var i=0u;i<samples;i++) {
        let phi = 6.283185307179586*(f32(i)+.5)/f32(samples);
        let xi = f32(reverseBits(i))*2.3283064365386963e-10;
        let c = sqrt((1.-xi)/max(1.+(a2-1.)*xi,1e-8));
        let s = sqrt(max(0.,1.-c*c));
        let h = vec3(cos(phi)*s,sin(phi)*s,c);
        let vh = max(dot(v,h),0.);
        let l = 2.*vh*h-v;
        let nl = max(l.z,0.);
        if (nl>0.) {
            let visibility = .5/max(nl*sqrt(a2+(1.-a2)*nv*nv)+nv*sqrt(a2+(1.-a2)*nl*nl),1e-12);
            let weight = 4.*visibility*nl*vh/max(h.z,1e-6);
            let fc = pow(1.-vh,5.);
            sum += vec2(1.-fc,fc)*weight;
        }
    }
    // At exact grazing, G2/G1(view) tends to one under the visible-normal PDF.
    // Preserve the sampled Schlick split while enforcing only this analytic limit.
    if (cosine <= 0.) { return sum / max(sum.x+sum.y,1e-8); }
    return sum/f32(samples);
}
''';
