name: planet
description: Native Flutter 3D and ECEF globe example.
publish_to: 'none'
version: 0.1.0+1
resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  crypto: ^3.0.7
  zyren:
    path: ../../packages/zyren
  zyren_pipeline:
    path: ../../packages/zyren_pipeline
  flutter:
    sdk: flutter
  flutter_zyren:
    path: ../../packages/flutter_zyren
  zyren_effects:
    path: ../../packages/zyren_effects
  zyren_geospatial:
    path: ../../packages/zyren_geospatial
  zyren_3d_tiles:
    path: ../../packages/zyren_3d_tiles

  shader_lab:
    path: ../shader_lab
  html: ^0.15.7
  url_launcher: ^6.3.2
  path_provider: ^2.1.6

dev_dependencies:
  zyren_game:
    path: ../../packages/zyren_game
  zyren_physics:
    path: ../../packages/zyren_physics
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/qualification/
    - assets/qualification/khronos-box/
