#!/usr/bin/env python3
"""Embed the pinned upstream catalogue after verifying its Git LFS object hash."""
import base64
import hashlib
from pathlib import Path
import sys

EXPECTED = '2fa0fd8318c85e9b0c8e318d84278d00e0610784e57a20e06b5715763bf4d5d6'
REVISION = 'eac103980f20c0956f2d3215833e73514be08462'
if len(sys.argv) != 2:
    raise SystemExit('Usage: python3 tool/embed_star_catalog.py /path/to/stars.bin')
data = Path(sys.argv[1]).read_bytes()
if len(data) != 90960 or hashlib.sha256(data).hexdigest() != EXPECTED:
    raise SystemExit('Catalogue differs from the pinned Git LFS object.')
encoded = base64.b64encode(data).decode('ascii')
output = Path(__file__).resolve().parents[1] / 'packages/zyren_geospatial/lib/src/atmosphere/star_data.dart'
header = f'''// Generated by tool/embed_star_catalog.py. Do not edit.
// three-geospatial {REVISION}, packages/atmosphere/assets/stars.bin
// SHA256 {EXPECTED}
// Copyright (c) 2024 Shota Matsuda. MIT, see THIRD_PARTY_NOTICES.md.
const brightStarData =
'''
output.write_text(header + '\n'.join("    '" + encoded[i:i+100] + "'" for i in range(0, len(encoded), 100)) + ';\n')
