import 'dart:io';

void main(List<String> arguments) {
  final root = File.fromUri(Platform.script).parent.parent.path;
  final source = File(
    '$root/packages/zyren_native/native/src/renderer/ggx_energy.wgsl',
  ).readAsStringSync();
  final output = File(
    '$root/packages/zyren/lib/src/rendering/ggx_energy_wgsl.dart',
  );
  final generated =
      '// Generated by tool/generate_ggx_energy.dart.\n'
      '// Edit the canonical native ggx_energy.wgsl and regenerate.\n'
      "const ggxEnergyWgsl = r'''\n$source''';\n";
  if (arguments.contains('--check')) {
    if (!output.existsSync() || output.readAsStringSync() != generated) {
      stderr.writeln('GGX energy shader constant needs regeneration.');
      exitCode = 1;
    }
  } else {
    output.writeAsStringSync(generated);
  }
}
