name: zyren_interaction_example
description: Native object hover, capture and selection example.
version: 0.1.0+1
publish_to: none
resolution: workspace
environment:
  sdk: '>=3.10.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_zyren:
    path: ../../flutter_zyren
  zyren:
    path: ../../zyren
  flutter_zyren_interaction:
    path: ../../flutter_zyren_interaction
  zyren_interaction:
    path: ..
  zyren_tools:
    path: ../../zyren_tools
  zyren_inspector:
    path: ../../zyren_inspector
  zyren_agents:
    path: ../../zyren_agents
  zyren_devtools:
    path: ../../zyren_devtools
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
