// Generated from native/include/gpu3d.h. Run dart run ffigen --config ffigen.yaml.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:gpu3d_native/src/bindings.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<
  ffi.Uint32 Function(
    ffi.Uint64,
    Fg2SurfaceKey,
    ffi.Pointer<Fg2SurfaceSnapshot>,
    ffi.Pointer<Fg2Error>,
  )
>()
external int fg2_apple_attach(
  int renderer,
  Fg2SurfaceKey key,
  ffi.Pointer<Fg2SurfaceSnapshot> output,
  ffi.Pointer<Fg2Error> error,
);

@ffi.Native<ffi.Uint32 Function()>()
external int fg2_apple_available();

@ffi.Native<ffi.Pointer<ffi.Void> Function(Fg2SurfaceKey)>()
external ffi.Pointer<ffi.Void> fg2_apple_copy_pixel_buffer(Fg2SurfaceKey key);

@ffi.Native<ffi.Uint64 Function()>()
external int fg2_apple_live_buffers();

@ffi.Native<ffi.Uint64 Function()>()
external int fg2_apple_presented_frames();

@ffi.Native<ffi.Uint64 Function()>()
external int fg2_apple_readback_bytes();

@ffi.Native<
  ffi.Uint32 Function(
    ffi.Uint64,
    Fg2SurfaceKey,
    ffi.Uint64,
    ffi.Uint64,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint64,
    ffi.Pointer<Fg2FrameReceipt>,
    ffi.Pointer<Fg2Error>,
  )
>()
external int fg2_apple_render(
  int renderer,
  Fg2SurfaceKey key,
  int epoch,
  int frame_id,
  ffi.Pointer<ffi.Uint8> json,
  int length,
  ffi.Pointer<Fg2FrameReceipt> output,
  ffi.Pointer<Fg2Error> error,
);

@ffi.Native<ffi.Uint64 Function()>()
external int fg2_runtime_token();

@ffi.Native<
  ffi.Uint32 Function(
    Fg2SurfaceKey,
    ffi.Pointer<Fg2SurfaceSnapshot>,
    ffi.Pointer<Fg2Error>,
  )
>()
external int fg2_surface_close(
  Fg2SurfaceKey key,
  ffi.Pointer<Fg2SurfaceSnapshot> output,
  ffi.Pointer<Fg2Error> error,
);

@ffi.Native<
  ffi.Uint32 Function(
    ffi.Pointer<Fg2SurfaceDescriptor>,
    ffi.Pointer<Fg2SurfaceSnapshot>,
    ffi.Pointer<Fg2Error>,
  )
>()
external int fg2_surface_create(
  ffi.Pointer<Fg2SurfaceDescriptor> descriptor,
  ffi.Pointer<Fg2SurfaceSnapshot> output,
  ffi.Pointer<Fg2Error> error,
);

@ffi.Native<
  ffi.Uint32 Function(
    Fg2SurfaceKey,
    ffi.Uint64,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Pointer<Fg2SurfaceSnapshot>,
    ffi.Pointer<Fg2Error>,
  )
>()
external int fg2_surface_resize(
  Fg2SurfaceKey key,
  int expected_epoch,
  int width,
  int height,
  ffi.Pointer<Fg2SurfaceSnapshot> output,
  ffi.Pointer<Fg2Error> error,
);

@ffi.Native<
  ffi.Uint32 Function(
    Fg2SurfaceKey,
    ffi.Pointer<Fg2SurfaceSnapshot>,
    ffi.Pointer<Fg2Error>,
  )
>()
external int fg2_surface_snapshot(
  Fg2SurfaceKey key,
  ffi.Pointer<Fg2SurfaceSnapshot> output,
  ffi.Pointer<Fg2Error> error,
);

@ffi.Native<
  ffi.Uint32 Function(
    Fg2SurfaceKey,
    ffi.Uint64,
    ffi.Uint32,
    ffi.Pointer<Fg2SurfaceSnapshot>,
    ffi.Pointer<Fg2Error>,
  )
>()
external int fg2_surface_suspend(
  Fg2SurfaceKey key,
  int expected_epoch,
  int suspended,
  ffi.Pointer<Fg2SurfaceSnapshot> output,
  ffi.Pointer<Fg2Error> error,
);

const int FG2_ABI_VERSION = 2;

final class Fg2Error extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int abi_version;

  @ffi.Uint32()
  external int code;

  @ffi.Uint32()
  external int message_length;

  @ffi.Array.multi([240])
  external ffi.Array<ffi.Uint8> message;
}

final class Fg2FrameReceipt extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int abi_version;

  @ffi.Uint64()
  external int epoch;

  @ffi.Uint64()
  external int frame_id;

  @ffi.Uint64()
  external int resident_bytes;

  @ffi.Uint64()
  external int readback_bytes;

  static ffi.Pointer<Fg2FrameReceipt> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int abi_version,
    required int epoch,
    required int frame_id,
    required int resident_bytes,
    required int readback_bytes,
  }) => $allocator<Fg2FrameReceipt>()
    ..ref.struct_size = struct_size
    ..ref.abi_version = abi_version
    ..ref.epoch = epoch
    ..ref.frame_id = frame_id
    ..ref.resident_bytes = resident_bytes
    ..ref.readback_bytes = readback_bytes;
}

enum Fg2Status {
  FG2_OK(0),
  FG2_INVALID_ARGUMENT(1),
  FG2_STALE_KEY(2),
  FG2_STALE_EPOCH(3),
  FG2_STALE_LEASE(4),
  FG2_DUPLICATE_COMPLETION(5),
  FG2_BACKPRESSURE(6),
  FG2_SUSPENDED(7),
  FG2_CLOSED(8),
  FG2_NOT_READY(9),
  FG2_BUDGET_EXCEEDED(10),
  FG2_EXHAUSTED(11),
  FG2_INTERNAL(12),
  FG2_TIMED_OUT(13),
  FG2_FRAME_SUPERSEDED(14);

  final int value;
  const Fg2Status(this.value);

  static Fg2Status fromValue(int value) => switch (value) {
    0 => FG2_OK,
    1 => FG2_INVALID_ARGUMENT,
    2 => FG2_STALE_KEY,
    3 => FG2_STALE_EPOCH,
    4 => FG2_STALE_LEASE,
    5 => FG2_DUPLICATE_COMPLETION,
    6 => FG2_BACKPRESSURE,
    7 => FG2_SUSPENDED,
    8 => FG2_CLOSED,
    9 => FG2_NOT_READY,
    10 => FG2_BUDGET_EXCEEDED,
    11 => FG2_EXHAUSTED,
    12 => FG2_INTERNAL,
    13 => FG2_TIMED_OUT,
    14 => FG2_FRAME_SUPERSEDED,
    _ => throw ArgumentError('Unknown value for Fg2Status: $value'),
  };
}

final class Fg2SurfaceDescriptor extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int abi_version;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Uint32()
  external int buffer_limit;

  @ffi.Uint32()
  external int max_in_flight;

  @ffi.Uint64()
  external int memory_limit;

  static ffi.Pointer<Fg2SurfaceDescriptor> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int abi_version,
    required int width,
    required int height,
    required int buffer_limit,
    required int max_in_flight,
    required int memory_limit,
  }) => $allocator<Fg2SurfaceDescriptor>()
    ..ref.struct_size = struct_size
    ..ref.abi_version = abi_version
    ..ref.width = width
    ..ref.height = height
    ..ref.buffer_limit = buffer_limit
    ..ref.max_in_flight = max_in_flight
    ..ref.memory_limit = memory_limit;
}

final class Fg2SurfaceKey extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int abi_version;

  @ffi.Uint64()
  external int runtime_token;

  @ffi.Uint64()
  external int slot;

  @ffi.Uint64()
  external int generation;

  static ffi.Pointer<Fg2SurfaceKey> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int abi_version,
    required int runtime_token,
    required int slot,
    required int generation,
  }) => $allocator<Fg2SurfaceKey>()
    ..ref.struct_size = struct_size
    ..ref.abi_version = abi_version
    ..ref.runtime_token = runtime_token
    ..ref.slot = slot
    ..ref.generation = generation;
}

final class Fg2SurfaceSnapshot extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int abi_version;

  external Fg2SurfaceKey key;

  @ffi.Uint64()
  external int epoch;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Uint32()
  external int state;

  @ffi.Uint32()
  external int reserved;
}

enum Fg2SurfaceState {
  FG2_SURFACE_CREATING(0),
  FG2_SURFACE_READY(1),
  FG2_SURFACE_SUSPENDED(2),
  FG2_SURFACE_CLOSING(3),
  FG2_SURFACE_CLOSED(4);

  final int value;
  const Fg2SurfaceState(this.value);

  static Fg2SurfaceState fromValue(int value) => switch (value) {
    0 => FG2_SURFACE_CREATING,
    1 => FG2_SURFACE_READY,
    2 => FG2_SURFACE_SUSPENDED,
    3 => FG2_SURFACE_CLOSING,
    4 => FG2_SURFACE_CLOSED,
    _ => throw ArgumentError('Unknown value for Fg2SurfaceState: $value'),
  };
}
