#!/usr/bin/env python3
"""Execute postprocessing 6.39.1 SMAA GLSL with its original lookup images."""
from pathlib import Path
import argparse,base64,hashlib,io,json,re,subprocess,tempfile
from PIL import Image
parser=argparse.ArgumentParser();parser.add_argument('reference',type=Path);args=parser.parse_args()
ref=args.reference.resolve();root=Path(__file__).resolve().parents[2]
assert json.loads((ref/'postprocessing/package.json').read_text())['version']=='6.39.1'
source=(ref/'postprocessing/build/index.js').read_text();hashes={}
def shader(name):
 s=re.search(r'var '+name+r' = `([^`]+)`;',source)[1];hashes[name]=hashlib.sha256(s.encode()).hexdigest();return s
images=[]
for name in ['area','search']:
 encoded=re.search(r'var '+name+r'ImageDataURL_default = "data:image/png;base64,([^"]+)"',source)[1]
 png=base64.b64decode(encoded);hashes[name+'Image']=hashlib.sha256(png).hexdigest()
 image=Image.open(io.BytesIO(png)).convert('RGBA');images.append((image.width,image.height,image.tobytes()))
# RLE keeps the exact source bytes without an image decoder dependency at runtime.
def rle(data):
 out=bytearray();i=0
 while i<len(data):
  j=i+1
  while j<len(data) and j-i<255 and data[j]==data[i]:j+=1
  out+=bytes([j-i,data[i]]);i=j
 return base64.b64encode(out).decode()
out=root/'packages/zyren_effects/lib/src/smaa_tables.dart'
text="// Source postprocessing 6.39.1 SMAA lookup images. Generated by tool/effects_reference/smaa.py.\nimport 'dart:convert';\nimport 'dart:typed_data';\n\nUint8List smaaTable(bool area) {\n final encoded=base64Decode(area ? _area : _search);\n final result=Uint8List(area ? 160*560*4 : 64*16*4);\n var offset=0;\n for(var i=0;i<encoded.length;i+=2){result.fillRange(offset,offset+encoded[i],encoded[i+1]);offset+=encoded[i];}\n if(offset!=result.length) throw StateError('Invalid SMAA table.');\n final rgba=Uint8List(result.length);\n final count=result.length~/4;\n for(var c=0;c<4;c++){for(var i=0;i<count;i++){rgba[i*4+c]=result[c*count+i];}}\n return rgba;\n}\n"
for name,(_,_,data) in zip(['area','search'],images):
 # Encode RGB pair for area and R for search; repeated alpha still compresses.
 encoded=rle(b''.join(data[c::4] for c in range(4)))
 text+=f"const _{name}=\n"+'\n'.join("    '"+encoded[i:i+100]+"'" for i in range(0,len(encoded),100))+";\n"
out.write_text(text)
compat=(root/'tool/cloud_reference/compat.hpp').read_text()+r'''
#include <vector>
using sampler2D=int;
using bvec2=int __attribute__((ext_vector_type(2)));using bvec4=int __attribute__((ext_vector_type(4)));
bvec2 B2(bool a){return {a,a};}bvec2 B2(vec2 a){return {a.x!=0,a.y!=0};}bvec4 B4(bool a){return {a,a,a,a};}
vec2 V2(vec2 a){return a;}vec4 V4(vec2 a,vec2 b){return {a.x,a.y,b.x,b.y};}vec4 V4(vec2 a,float b,float c){return {a.x,a.y,b,c};}
vec2 abs(vec2 v){return {abs(v.x),abs(v.y)};}vec3 abs(vec3 v){return {abs(v.x),abs(v.y),abs(v.z)};}
vec2 floor(vec2 v){return {floor(v.x),floor(v.y)};}vec2 round(vec2 v){return floor(v+.5f);}vec4 round(vec4 v){return floor(v+.5f);}
vec2 sqrt(vec2 v){return {sqrtf(v.x),sqrtf(v.y)};}vec2 max(vec2 a,vec2 b){return {max(a.x,b.x),max(a.y,b.y)};}
vec2 clamp(vec2 a,float lo,float hi){return {clamp(a.x,lo,hi),clamp(a.y,lo,hi)};}
vec2 step(vec2 a,vec2 b){return {b.x<a.x?0.f:1.f,b.y<a.y?0.f:1.f};}vec2 step(float a,vec2 b){return step(V2(a),b);}
vec2 movec(bvec2 c,vec2 v,vec2 x){if(c.x)v.x=x.x;if(c.y)v.y=x.y;return v;}
vec4 movec(bvec4 c,vec4 v,vec4 x){for(int i=0;i<4;i++)if(c[i])v[i]=x[i];return v;}
vec3 position;vec4 gl_Position,gl_FragColor;int width=32,height=24;
struct Image {int w,h;std::vector<vec4> pixels;};Image maps[5];
vec4 texture2D(int id,vec2 uv){const auto &im=maps[id];vec2 p=uv*V2(im.w,im.h)-.5f;for(int k=0;k<2;k++)if(std::abs(p[k]-std::round(p[k]))<1e-4f)p[k]=std::round(p[k]);int bx=std::floor(p.x),by=std::floor(p.y);vec2 f=p-floor(p);vec4 value=V4(0);
 if(id==4){int x=clamp((int)std::floor(uv.x*im.w),0,im.w-1),y=clamp((int)std::floor(uv.y*im.h),0,im.h-1);return im.pixels[(im.h-1-y)*im.w+x];}
 for(int y=0;y<2;y++)for(int x=0;x<2;x++){int ix=clamp(bx+x,0,im.w-1),iy=clamp(by+y,0,im.h-1);if(id!=3)iy=im.h-1-iy;value+=im.pixels[iy*im.w+ix]*(x?f.x:1-f.x)*(y?f.y:1-f.y);}return value;
}
void values(vec4 v){for(int k=0;k<4;k++){if(k)std::cout<<',';std::cout<<v[k];}}
void array(const Image &im){std::cout<<'[';for(int i=0;i<im.pixels.size();i++){if(i)std::cout<<',';values(im.pixels[i]);}std::cout<<']';}
'''
def remove_function(s,signature):
 start=s.index(signature);a=s.index('{',start);depth=1;b=a+1
 while depth:
  if s[b]=='{':depth+=1
  if s[b]=='}':depth-=1
  b+=1
 return s[:start]+s[b:]
def translate(s,main):
 if 'void movec' in s:
  s=remove_function(s,'void movec');s=remove_function(s,'void movec')
 s=re.sub(r'#include[^\n]*','',s)
 s=re.sub(r'\b(?:uniform|varying|lowp|mediump|highp)\s+','',s)
 s=s.replace('out vec2 e','vec2 &e').replace('out vec4 outputColor','vec4 &outputColor')
 s=s.replace('inout vec2 weights','vec2 weights')
 s=s.replace('void detectHorizontalCornerPattern','vec2 detectHorizontalCornerPattern').replace('void detectVerticalCornerPattern','vec2 detectVerticalCornerPattern')
 # The corner functions end at these exact preprocessor boundaries.
 s=s.replace('#endif\n}vec2 detectVerticalCornerPattern','#endif\nreturn weights;}vec2 detectVerticalCornerPattern')
 s=s.replace('#endif\n}void main()','#endif\nreturn weights;}void main()')
 s=s.replace('detectHorizontalCornerPattern(weights.rg,','weights.rg=detectHorizontalCornerPattern(weights.rg,').replace('detectVerticalCornerPattern(weights.ba,','weights.ba=detectVerticalCornerPattern(weights.ba,')
 s=s.replace('movec(bvec2(step(0.9,d.zw)),cc,vec2(0.0));','cc=movec(bvec2(step(0.9,d.zw)),cc,vec2(0.0));')
 s=s.replace('movec(bvec4(h),blendingOffset,','blendingOffset=movec(bvec4(h),blendingOffset,').replace('movec(bvec2(h),blendingWeight,','blendingWeight=movec(bvec2(h),blendingWeight,')
 s=re.sub(r'\b(?:const in|in)\s+','',s).replace('discard;','return;')
 s=s.replace('void main()',f'void {main}()')
 s=re.sub(r'\bbvec([24])\(',r'B\1(',s);s=re.sub(r'\bvec([234])\(',r'V\1(',s)
 return re.sub(r'(?<![\w.])(\d+\.\d*(?:[eE][+-]?\d+)?|\d+[eE][+-]?\d+)(?![\w.])',r'\1f',s)
def stage(v,f,name):
 vertex=shader(v);fragment=shader(f)
 declarations=set(re.findall(r'(?:uniform|varying) [^;]+;',vertex))
 fragment=re.sub(r'(?:uniform|varying) [^;]+;',lambda m:'' if m[0] in declarations else m[0],fragment)
 return 'namespace '+name+' {\n'+translate(vertex,'vertexMain')+'\n'+translate(fragment,'fragmentMain')+'\n}\n'
base=stage('edge_detection_default2','edge_detection_default','edge')+stage('smaa_weights_default2','smaa_weights_default','weight')
base+=stage('smaa_default2','smaa_default','blend').replace('namespace blend {','namespace blend { vec2 texelSize; sampler2D inputBuffer;')
cases=[]
for preset,(threshold,steps,diag) in enumerate([(.15,4,0),(.1,8,0),(.1,16,8),(.05,32,16)]):
 defines=f'''\n#undef __VERSION__
#define __VERSION__ 300
#define EDGE_DETECTION_MODE 2
#define PREDICATION_MODE 0
#define EDGE_THRESHOLD {threshold}f
#define LOCAL_CONTRAST_ADAPTATION_FACTOR 2.f
#define MAX_SEARCH_STEPS_INT {steps}
#define MAX_SEARCH_STEPS_FLOAT {steps}.f
#define MAX_SEARCH_STEPS_DIAG_INT {diag}
#define AREATEX_MAX_DISTANCE 16.f
#define AREATEX_MAX_DISTANCE_DIAG 20.f
#define AREATEX_PIXEL_SIZE (1.f/V2(160,560))
#define AREATEX_SUBTEX_SIZE (1.f/7.f)
#define SEARCHTEX_SIZE V2(66,33)
#define SEARCHTEX_PACKED_SIZE V2(64,16)
#define CORNER_ROUNDING_NORM .25f
'''+('' if diag else '#define DISABLE_DIAG_DETECTION\n#define DISABLE_CORNER_DETECTION\n')
 main='int main(){\n'
 for id,(w,h,data) in enumerate(images,3):
  main+=f'unsigned char table{id}[]={{'+','.join(map(str,data))+'};\n'
  main+=f'maps[{id}].w={w};maps[{id}].h={h};for(int i=0;i<{w*h*4};i+=4)maps[{id}].pixels.push_back(V4(table{id}[i],table{id}[i+1],table{id}[i+2],table{id}[i+3])/255.f);\n'
 main+=r'''
edge::inputBuffer=0;weight::inputBuffer=1;weight::areaTexture=3;weight::searchTexture=4;blend::weightMap=2;blend::inputBuffer=0;
edge::texelSize=weight::texelSize=blend::texelSize=V2(1.f/width,1.f/height);weight::resolution=V2(width,height);
std::cout<<std::setprecision(9)<<'[';
for(int pattern=0;pattern<6;pattern++){
 for(int id=0;id<3;id++){maps[id].w=width;maps[id].h=height;maps[id].pixels.clear();}
 for(int y=0;y<height;y++)for(int x=0;x<width;x++){
 bool lit=pattern==0?true:pattern==1?x>y*1.35f+2:pattern==2?(x>5&&x<26&&y>5&&y<18):pattern==3?(y==11||x==15):pattern==4?x/4>y/3:(x/3+y/3)%2;
 maps[0].pixels.push_back(lit?(pattern==4?V4(.4f,.1f,.2f,.5f):V4(.8f,.5f,.2f,1)):V4(.02f,.03f,.04f,1));
 }
 for(int y=0;y<height;y++)for(int x=0;x<width;x++){
 position=V3((x+.5f)/width*2-1,(1-(y+.5f)/height)*2-1,0);gl_FragColor=V4(0,0,0,1);edge::vertexMain();edge::fragmentMain();maps[1].pixels.push_back(gl_FragColor);
 }
 for(int y=0;y<height;y++)for(int x=0;x<width;x++){
 position=V3((x+.5f)/width*2-1,(1-(y+.5f)/height)*2-1,0);gl_FragColor=V4(0);weight::vertexMain();weight::fragmentMain();maps[2].pixels.push_back(floor(gl_FragColor*255.f+.5f)/255.f);
 }
 if(pattern)std::cout<<',';std::cout<<"{\"pattern\":"<<pattern<<",\"input\":";array(maps[0]);std::cout<<",\"edges\":";array(maps[1]);std::cout<<",\"weights\":";array(maps[2]);std::cout<<",\"output\":[";
 for(int y=0;y<height;y++)for(int x=0;x<width;x++){
 vec2 uv=V2((x+.5f)/width,1-(y+.5f)/height);vec4 color;blend::mainSupport(uv);blend::mainImage(maps[0].pixels[y*width+x],uv,color);if(x||y)std::cout<<',';values(color);
 }std::cout<<"]}";
}std::cout<<']';}
'''
 with tempfile.TemporaryDirectory(prefix='zyren-smaa-') as t:
  p=Path(t);(p/'main.cpp').write_text(compat+defines+base+main)
  subprocess.run(['clang++','-O2','-std=c++17','-ffp-contract=off',str(p/'main.cpp'),'-o',str(p/'run')],check=True)
  cases.extend(dict(c,preset=preset) for c in json.loads(subprocess.check_output([str(p/'run')],text=True)))
(root/'packages/zyren_effects/test/fixtures/smaa.json').write_text(json.dumps({'reference':'postprocessing 6.39.1 SMAA','sources':hashes,'width':32,'height':24,'cases':cases})+'\n')
print(f'{len(cases)} original SMAA pipeline cases and two lookup tables')
