import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'package:crypto/crypto.dart';
import 'package:test/test.dart';
import 'package:zyren_game_ai/artifact.dart';

// Optional exact-byte qualification inputs are generated by the Python T5 gate.
// Trial paths are never accepted application assets merely because tests read them.
void main() {
  final directory = Platform.environment['ZYREN_INT8_TRIAL'];
  for (final family in ['guard', 'vehicle']) {
    test(
      'exact $family int8 baseline proof and tamper rejection',
      () {
        final folder = Directory('$directory/$family');
        final manifest = File('${folder.path}/bundle.json').readAsBytesSync();
        final files = {
          for (final name in ModelArtifact.fileNames)
            name: File('${folder.path}/$name').readAsBytesSync(),
        };
        final artifact = ModelArtifact.decode(manifest, files);
        expect(artifact.precision, 'int8');
        expect(artifact.fixedHz, 50);
        expect(artifact.evaluation.accepted, isTrue);
        final original = utf8.decode(files['provenance.json']!);
        void rejects(String from, String to, String reason) {
          expect(original, contains(from));
          final changed = Uint8List.fromList(
            utf8.encode(original.replaceFirst(from, to)),
          );
          final envelope = jsonDecode(utf8.decode(manifest)) as Map;
          final row = (envelope['files'] as List).cast<Map>().singleWhere(
            (e) => e['path'] == 'provenance.json',
          );
          row['bytes'] = changed.length;
          row['sha256'] = sha256.convert(changed).toString();
          expect(
            () => ModelArtifact.decode(
              Uint8List.fromList(utf8.encode(jsonEncode(envelope))),
              {...files, 'provenance.json': changed},
            ),
            throwsA(
              isA<FormatException>().having(
                (e) => e.message,
                'reason',
                contains(reason),
              ),
            ),
          );
        }

        rejects(
          '"calibration_partition":"train"',
          '"calibration_partition":"test"',
          'calibration',
        );
        rejects(
          '"calibration_steps":1000',
          '"calibration_steps":2001',
          'calibration',
        );
        rejects('"success_loss":0.0', '"success_loss":0.01', 'loss');
        final proof = jsonDecode(original)['quantization'] as Map;
        rejects(
          '"baseline_bundle_hash":"${proof['baseline_bundle_hash']}"',
          '"baseline_bundle_hash":"${'f' * 64}"',
          'baseline',
        );
        rejects(
          '"typed_controller_steps":1000',
          '"typed_controller_steps":999',
          'native parity',
        );
        rejects('"live_results":0', '"live_results":1', 'native parity');
      },
      skip: directory == null
          ? 'Set ZYREN_INT8_TRIAL to exact T5 proof-complete trials.'
          : false,
    );
  }
}
